### ISSUE TITLE
not working in ios

### ISSUE THREAD

**Issue by SanchaiAhilan** [ukieTux/flutter_toggle_tab#14]
The flutter toggle tab is not wroking in iPhone. The Tab bar is displayed as expected, but when clicked the function "selectedLabelIndex" is not called. It is working fine on android though. Please help me find a fix.

**Comment by Lzyct** [comment]
> The flutter toggle tab is not wroking in iPhone. The Tab bar is displayed as expected, but when clicked the function "selectedLabelIndex" is not called. It is working fine on android though. Please help me find a fix.

Can you provide the video related this issue @SanchaiAhilan ?

Thanks

**Comment by HenrikThien** [comment]
Can you post a code snippet @SanchaiAhilan ?
For me the latest version is working. Maybe you are missing on a setState to refresh the ui?

**Comment by SanchaiAhilan** [comment]
The problem is not with the ToggleTab. The issue was with using multiple scaffolds in stack in iOS
