### ISSUE TITLE
How to add margin or padding for buttons 

### ISSUE THREAD

**Issue by VladRoscaDev** [ukieTux/flutter_toggle_tab#4]
I want to provide a margin top and bottom for the buttons but there is no such feature, do you think you can add it? I want it to achieve this design: 
![image](https://user-images.githubusercontent.com/58691756/113583740-b7233080-9632-11eb-9f34-356fa6678a05.png)

**Comment by Lzyct** [comment]
I have added support for marginSelected tab, you can see on README for more detail
