### ISSUE TITLE
FlutterToggleTab range error

### ISSUE THREAD

**Issue by kesbeast23** [ukieTux/flutter_toggle_tab#7]
Basic implementation:
FlutterToggleTab(
                                  width: 20,
                                  height: 30,
                                  borderRadius: 15,
                                  initialIndex: 0,
                                  selectedTextStyle: TextStyle(
                                      color: Colors.white,
                                      fontSize: 10,
                                      fontWeight: FontWeight.w600),
                                  unSelectedTextStyle: TextStyle(
                                      color: Colors.grey,
                                      fontSize: 10,
                                      fontWeight: FontWeight.w400),
                                  labels: ["", ""],
                                  icons: [Icons.lock_outlined, Icons.lock_open],
                                  selectedLabelIndex: (index) {
                                    print("Selected Index $index");
                                  },
                                ),

Error message:

Exception caught by widgets library ═══════════════════════════════════
The following RangeError was thrown building:
RangeError (index): Invalid value: Not in inclusive range 0..1: 2

When the exception was thrown, this was the stack
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      _FlutterToggleTabState.build.<anonymous closure> (package:flutter_toggle_tab/flutter_toggle_tab.dart:149:62)
#2      SliverChildBuilderDelegate.build
package:flutter/…/widgets/sliver.dart:455
#3      SliverMultiBoxAdaptorElement._build
package:flutter/…/widgets/sliver.dart:1201
#4      SliverMultiBoxAdaptorElement.performRebuild.processElement
package:flutter/…/widgets/sliver.dart:1145

**Comment by Lzyct** [comment]
![image](https://user-images.githubusercontent.com/1531684/117921968-3f78ad80-b324-11eb-95d6-5c1971945895.png)

Where is the problem? I didn't find that problem @kesbeast23

**Comment by kesbeast23** [comment]
thid is what am getting :


════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..1: 2


for this version:
flutter_toggle_tab: ^1.1.0

**Comment by Lzyct** [comment]
Hmm, I just copy-paste from your code, and there no issue about range error-index

**Comment by ganadevprajapathy** [comment]
Getting the same error. +1.

**Comment by Lzyct** [comment]
Can you provide detail like type `flutter doctor` ?

Because I'm using flutter 2.x and I didn't find that error

**Comment by ganadevprajapathy** [comment]
[✓] Flutter (Channel beta, 2.2.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

Following is the error log.

 ======== Exception caught by widgets library =======================================================
The following RangeError was thrown building:
RangeError (index): Invalid value: Not in inclusive range 0..1: 2

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      _FlutterToggleTabState.build.<anonymous closure> (package:flutter_toggle_tab/flutter_toggle_tab.dart:148:62)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1213:28)
#4      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1146:67)

**Comment by Lzyct** [comment]
It's fixed in version 1.1.2

**Comment by rvngbrl** [comment]
version 1.1.3 has bug again the error "RangeError (index): Invalid value: Not in inclusive range 0..1: 2" is not showing but if you slide the toggle to right or left it will add another list of button.

**Comment by Lzyct** [comment]
> version 1.1.3 has bug again the error "RangeError (index): Invalid value: Not in inclusive range 0..1: 2" is not showing but if you slide the toggle to right or left it will add another list of button.

Fix duplicate button in latest version 1.1.4
